name: attendance_qr
version: 1.0.0
publish_to: 'none'
description: App móvil Flutter para control de asistencia de profesores mediante QR.
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.0
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.0
  http: ^1.2.2
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
